version: '3.9'

services:
  cesilicious_auth:
    build: /cesilicious_auth
    environment:
      JWT_SECRET_KEY: 'cesilicious'
    networks:
      - api-network
    container_name: cesilicious_auth
    depends_on:
      - db
    links:
      - db

  cesilicious_delivery:
    build: /cesilicious_delivery
    environment:
      MONGODB_URI: 'mongodb+srv://admin:IyCtbSX4rda45h6C@cesilicious.w0zbplf.mongodb.net/deliveries/'
    networks:
      - api-network
    container_name: cesilicious_delivery

  cesilicious_order:
    build: /cesilicious_orders
    environment:
      MONGODB_URI: 'mongodb+srv://admin:IyCtbSX4rda45h6C@cesilicious.w0zbplf.mongodb.net/orders/'
    networks:
      - api-network
    container_name: cesilicious_order

  cesilicious_restaurant:
    build: /cesilicious_restaurant
    environment:
      MONGODB_URI: 'mongodb+srv://admin:IyCtbSX4rda45h6C@cesilicious.w0zbplf.mongodb.net/restaurants/'
    networks:
      - api-network
    container_name: cesilicious_restaurant

  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - cesilicious_auth
      - cesilicious_delivery
      - cesilicious_order
      - cesilicious_restaurant
    ports:
      - 80:80
    networks:
      - api-network

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cesiliciousql
    ports:
      - 5432:5432
    networks:
      - api-network
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql

networks:
  api-network:
    driver: bridge

volumes:
  db:
    driver: local